[Interface]
PrivateKey = PLACEHOLDER_REPLACED_BY_SCRIPT
Address = 10.10.99.2/24

[Peer]
PublicKey = DH8USbJ8mwENjtnqVSxLSBTno3pJp3Mydivs8rKdcEk=
Endpoint = vpn.citadelsolutions.tech:51820
AllowedIPs = 10.10.20.35/32
PersistentKeepalive = 25